solana:
  target: dev
  outputs:
    dev:
      type: clickhouse
      driver: http
      schema: dbt
      host: jsxrmzzbl6.europe-west4.gcp.clickhouse.cloud
      user: jgligorevic
      password: 'Jolesrbine-1994'
      secure: True
      verify: False